### ISSUE TITLE
Olá, gostaria de estudar a possibilidade de implementação de código assíncrono.

### ISSUE THREAD

**Issue by Lamarcke** [matheusfelipeog/filometro#35]
Curti a ideia do projeto, e gostaria de saber se você está interessado em colaborar parar criar novas classes/métodos assíncronas.
Pelo que entendi, você está fazendo scraping do site De Olho na Fila, correto? (ainda tenho que acessar e entender melhor o código quando tiver um tempo)

Provavelmente a única parte que iria beneficiar desse tipo de implementação seria justamente essa de requisição. O resto do código aparentemente não faz nenhuma computação pesada.

**Comment by matheusfelipeog** [comment]
Olá @Lamarcke 👋

Obrigado por abrir essa issue e pelo interesse em colaborar com o projeto ;)

Bem, no momento isso não é necessário e não trará benefício. Todos os dados são obtidos em apenas uma requisição (que já é rápida o suficiente), esses mesmos dados não são atualizados em pequenos intervalos de tempo pelas unidades e tal recurso pode aplicar uma carga desnecessária nos servidores. Portanto, acredito que não seja necessário.

**Comment by Lamarcke** [comment]
Entendo perfeitamente, você tem razão. Estou fechando o issue.
